//holds the information for a single data instance

#include "globals.hpp"
#include <iostream>

#pragma once

using namespace std;

class Data {
public:

    Data() {
        name = "";
        for(int i = 0; i < 3; i++) {
            name_val[0] = 0;
        }
    }

    //reads in string to get instance data
    //assumes s follows specific format of given data file
    //otherwise it will crash!
    void process(string s) {
        int start = 0;
        int end = 0;
        string val = "";
        for(int i = 0; i < 4; i++) {
            while(end < s.length() && s.at(end) != ',') {
                end++;
            }
            val = s.substr(start, end-start);
            vals[i] = stod(val);
            end++;
            start = end;
        }

        name = s.substr(start, s.length() - start);
        if(name == SETOSA) {
            name_val[0] = 1;
        } else if(name == VERSICOLOR) {
            name_val[1] = 1;
        } else if(name == VIRGINICA){
            name_val[2] = 1;
        }   
    }

    //for data generated by user input
    void process(double sl, double sw, double pl, double pw) {
        vals[0] = sl;
        vals[1] = sw;
        vals[2] = pl;
        vals[3] = pw;
    }

    void print() {
        cout << name << ": " << vals[0] << ", " << vals[1] << ", " 
        << vals[2] << ", " << vals[3] << endl;
    }

    //assumes 0 <= i <= 3
    double get_val(int i) {
        return vals[i];
    }

    //returns name encoding
    int *get_name() {
        return name_val;
    }

    std::string get_name_string() {
        return name;
    }

private:

    double* vals = new double[4];

    //an array of 4 doubles, representing in order:
    //sepal length, sepal width, petal length, petal width
    std::string name;

    //one-hot encoding
    //setosa = 1 0 0, versicolor = 0 1 0, verginica = 0 0 1
    int* name_val = new int[3];

};
